import type { Metadata } from 'next';
import Link from 'next/link';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ThemeToggle from './_components/themeToggle';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white dark:bg-black text-black dark:text-white">
        <header className="dark:bg-gradient-to-bl from-slate-950 via-slate-900 to-slate-950 border-b border-slate-200/80 dark:border-slate-800/80 p-4 flex items-center justify-end gap-4">
          <Link
            href="/posts"
            className="text-sm font-medium text-slate-700 dark:text-slate-300 hover:text-purple-700 dark:hover:text-purple-300 transition-colors mr-auto"
          >
            Posts
          </Link>
          <ThemeToggle />
        </header>

        {children}
      </body>
    </html>
  );
}
